---
title: "ESM206 Assignment 4"
author: "Anna Abelman and Emma Friedl"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Attaching Packages
library(tidyverse)
library(janitor)
library(here)
library(DT)

# Read in data
lobster <- read_csv(here("raw_data", "lobster_abundance_sbc_lter.csv"),
                    na = "-99999") %>% 
  clean_names()
```

```{r}
lobster_tidy <- lobster %>% 
  uncount(count)
```


# Introduction:

# Data Methods

# Results:

## A.

Naples and IV are MPA
```{r}
lobster_site <- lobster_tidy %>% 
  group_by(year)%>% 
  count(site) %>% 
  mutate(highlight = ifelse(site == "IVEE" | site == "NAPL", "MPA", "Non-MPA"))

  ggplot(data = lobster_site, aes(x = year, y = n, group = site, color = highlight))+
  geom_line()+
    scale_color_manual(values = c("blue", "green"))+
    scale_size_manual(values = c(1.5,2))+
    theme(legend.position = "none")+
  theme_minimal()+
  labs(x = "Year", y = "Number of Lobsters", title = "Number of Lobsters Per Site, 2012-2018")+
    scale_x_continuous(expand = c(0,0))
  
```

## B.
```{r}
lobster_size <- lobster_tidy %>%
  select(year, site, size_mm) %>% 
  filter(year == c("2012","2018"))

lobster_size$year <- as.factor(lobster_size$year)

site_list <- unique(lobster_size$site)

#for (i in site_list) {
  #graph <- ggplot(subset(lobster_size,
   #                      lobster_size$site == i), 
    #              aes(x = sites, y = size_mm, fill = year)) +
 # geom_violin(position = "dodge", show.legend = FALSE, trim = FALSE)+
  #  facet_wrap(sites)
   # print(graph)
#}

 graph <- ggplot(lobster_size, aes(x = site, y = size_mm, fill = year)) +
  geom_violin(position = "dodge", show.legend = FALSE, trim = FALSE)+
    facet_wrap(~site, scales = "free")

graph
  
```

```{r}
lobster_size_2012 <- lobster_tidy %>% 
  filter(year == "2012")

lobster_size_2018 <- lobster_tidy %>% 
  filter(year == "2018")

ggplot()+
  geom_violin(data = lobster_size_2012, position = "dodge",
              aes(x = site, y = size_mm, ))+
  geom_violin(data = lobster_size_2018,position = "dodge",
              aes(x = site, y = size_mm, fill = year))+
  facet_wrap(vars(site))
```


## C.
```{r}
#create a vector containing either "MPA" or "Non_MPA"
#corresponsing to the site
sites = lobster_tidy$site
mpa_sites <- ifelse(sites == "IVEE" | sites == "NAPL", 
                    "MPA", "Non_MPA")

lobster_mean_size <- lobster_tidy %>% 
  mutate(protected_status = mpa_sites) %>% 
  select(year, size_mm, protected_status) %>% 
  filter(year == c("2012","2018")) %>% 
  group_by(protected_status, year) %>% 
  mutate(mean_size = mean(size_mm)) 

lobster_mean_size$year <- as.factor(lobster_mean_size$year)

ggplot(lobster_mean_size, 
       aes(fill = protected_status, x = year, y = mean_size)) +
  geom_col(position="dodge")

```


# Summary:


# References:











